# Generated by Django 4.0.3 on 2022-03-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('patente', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('CM', 'Compacto'), ('SD', 'Sedan'), ('MV', 'Monovolumen'), ('UT', 'Utilitario'), ('LJ', 'Lujo')], max_length=50)),
                ('cantidad_puertas', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('patente', models.CharField(max_length=200)),
                ('cilindrada', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
