# Generated by Django 4.0.3 on 2022-03-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='automovil',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='moto',
            name='cilindrada',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='Desperfecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('mano_de_obra', models.IntegerField()),
                ('tiempo', models.TimeField()),
                ('respuestos', models.ManyToManyField(to='budget_app.respuesto')),
            ],
        ),
        migrations.AddField(
            model_name='automovil',
            name='desperfectos',
            field=models.ManyToManyField(to='budget_app.desperfecto'),
        ),
        migrations.AddField(
            model_name='moto',
            name='desperfectos',
            field=models.ManyToManyField(to='budget_app.desperfecto'),
        ),
    ]
