# Generated by Django 4.0.3 on 2022-03-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0005_alter_respuesto_motocicletas_alter_respuesto_precio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField(blank=True, default=0)),
                ('size', models.CharField(blank=True, choices=[('L', 'Grande'), ('M', 'Mediano'), ('S', 'Pequeño')], default='M', max_length=20)),
                ('importado', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='desperfecto',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='desperfecto',
            name='respuestos',
        ),
        migrations.RemoveField(
            model_name='desperfecto',
            name='tiempo',
        ),
        migrations.AddField(
            model_name='desperfecto',
            name='tiempo_dias',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='automovil',
            name='cantidad_puertas',
            field=models.IntegerField(choices=[(2, 2), (4, 4)]),
        ),
        migrations.AlterField(
            model_name='automovil',
            name='tipo',
            field=models.CharField(choices=[('CM', 'Compacto'), ('MV', 'Monovolumen'), ('SD', 'Sedan'), ('UT', 'Utilitario'), ('LJ', 'Lujo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='desperfecto',
            name='descripcion',
            field=models.TextField(blank=True, default='Describe el desperfecto...'),
        ),
        migrations.AlterField(
            model_name='moto',
            name='cilindrada',
            field=models.CharField(choices=[('S', '125 cc'), ('M', '250 cc'), ('L', '500 cc')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Respuesto',
        ),
        migrations.AddField(
            model_name='desperfecto',
            name='repuestos',
            field=models.ManyToManyField(to='budget_app.repuesto'),
        ),
    ]
