# Generated by Django 4.0.3 on 2022-04-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desperfecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, default='Describe el desperfecto...')),
                ('mano_de_obra', models.IntegerField()),
                ('tiempo_dias', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField(blank=True, default=0)),
                ('size', models.CharField(blank=True, choices=[('L', 'Grande'), ('M', 'Mediano'), ('S', 'Pequeño')], default='M', max_length=20)),
                ('importado', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('patente', models.CharField(max_length=200)),
                ('cilindrada', models.CharField(choices=[('S', '125 cc'), ('M', '250 cc'), ('L', '500 cc')], max_length=10)),
                ('desperfectos', models.ManyToManyField(to='budget_app.desperfecto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='desperfecto',
            name='repuestos',
            field=models.ManyToManyField(to='budget_app.repuesto'),
        ),
        migrations.CreateModel(
            name='Automovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('patente', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('CM', 'Compacto'), ('MV', 'Monovolumen'), ('SD', 'Sedan'), ('UT', 'Utilitario'), ('LJ', 'Lujo')], max_length=50)),
                ('cantidad_puertas', models.IntegerField(choices=[(2, 2), (4, 4)])),
                ('desperfectos', models.ManyToManyField(to='budget_app.desperfecto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
