# Generated by Django 4.0.3 on 2022-03-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0002_respuesto_alter_automovil_tipo_alter_moto_cilindrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='desperfecto',
            name='nombre',
            field=models.CharField(default='nombre', max_length=200),
        ),
    ]
