# Generated by Django 4.0.3 on 2022-03-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0004_respuesto_importado_respuesto_motocicletas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesto',
            name='motocicletas',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='respuesto',
            name='precio',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='respuesto',
            name='size',
            field=models.CharField(blank=True, choices=[('L', 'Grande'), ('M', 'Mediano'), ('S', 'Pequeño')], default='Mediano', max_length=20),
        ),
    ]
